import Notificatioin from "@/components/Notificatioin";
import "./globals.css";
import type { Metadata } from "next";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div>
          <div className="sticky top-0 z-50">
          <Notificatioin/>
          <Navbar/>
          </div>
          {children}
          <Footer/>
        </div>
      </body>
    </html>
  );
}
